version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    container_name: app
    depends_on:
      - db
    environment:
      DATABASE_URL: mongodb://root:root@db/invoice-app?authSource=admin&tls=false
      VITE_API_URL: http://localhost:3000
    ports:
      - "3000:3000"
      - "8000:8000"
    restart: always

  db:
    attach: false
    build:
      context: ./mongo/
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: |
        test $$(mongosh --quiet -u root -p root --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'db' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 30s

volumes:
  mongodb_data:
