FROM node:21 as base
WORKDIR /app

FROM base as deps
COPY package*.json ./
COPY apps apps/
COPY packages packages/
RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -print | xargs rm -rf
RUN find apps \! -name "package.json" -mindepth 2 -maxdepth 2 -print | xargs rm -rf
RUN npm install

FROM base as dev
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/vite/node_modules ./apps/vite/node_modules
COPY ./ ./
RUN npx prisma generate
EXPOSE 3000
EXPOSE 8000
